app:
    name: notification-service
    env: ${APP_ENV}
    senderType: ${APP_SENDERTYPE}

database:
    host: ${DATABASE_HOST}
    port: ${DATABASE_PORT}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    dbname: ${DATABASE_DBNAME}
    sslmode: ${DATABASE_SSLMODE}

rabbitmq:
    url: ${RABBITMQ_URL}

smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    from: ${SMTP_FROM}
    fromName: ${SMTP_FROM_NAME}
    tls: ${SMTP_TLS}
